### ISSUE TITLE
 path in settings.php goes to '/sites/all/modules/contrib/stacksight

### ISSUE THREAD

**Issue by hermanlinnovate** [stacksight/drupal#18]
When installed the module through the installation interface, the module was installed in /sites/all/modules/stacksight. the result was a php error

**Comment by igor-lemon** [comment]
What? What is settings.php in "/sites/all/modules/contrib/stacksight" ? What is error?

**Comment by hermanlinnovate** [comment]
Not able to remove stucksight installation on drupal + the drupal local
path had similar bug as well as wordpress one.

Sent with MailTrack
https://mailtrack.io/install?source=signature&lang=en&referral=herman@linnovate.net&idSignature=22

On Thu, Feb 11, 2016 at 10:36 AM, Igor Kozlovsky notifications@github.com
wrote:

> What? What is settings.php in "/sites/all/modules/contrib/stacksight" ?
> What is error?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/stacksight/drupal/issues/18#issuecomment-182764867.

## 

Lior Herman
herman@linnovate.net
Skype: lior.herman1
M: +972-52-629-8889

**Comment by liorkesos** [comment]
@herman please add screenshots to bug reports.
@igor - Herman is talking about the fact that the guidelines in the module
settings page and the online installation guidelines are not in sync

**Comment by igor-lemon** [comment]
@hermanlinnovate What is Drupal version? Because I installed v7 and v8 from admin interface and installation did success. On v6 you should install module manually to the modules directory. I don't understand what you mean about "the module was installed in /sites/all/modules/stacksight" because it is correct path.
How do you install modules? I need full description because I need repeat all you actions on my side.
